### ISSUE TITLE
SQL injectable

### ISSUE THREAD

**Issue by pintman** [LuBlaBo/Zeiterfassung#2]
Your code is open to SQL injection. Enter `  ' OR 1 -- ` for checkin and everybody will be checked in. Same holds for checkout.

The problem arises from the following lines:

https://github.com/LuBlaBo/Zeiterfassung/blob/229da34fa7ebb266c616c8f05182b4eb3899d624/Server.py#L86

https://github.com/LuBlaBo/Zeiterfassung/blob/229da34fa7ebb266c616c8f05182b4eb3899d624/Server.py#L107

**Comment by LuBlaBo** [comment]
I have now adapted the code to search for a ' in the string. If this is the case, an error message is displayed.
My solution:

At checkin section
    elif "'" in checkin_id:
        msg = "Zeichen nicht zulässig!"

At checkout section
    elif "'" in checkout_id:
        msg = "Zeichen nicht zulässig!"

Do I need to make any more adjustments?

**Comment by pintman** [comment]
Not a bad idea, but you can do better. :)

> You shouldn’t assemble your query using Python’s string operations because doing so is insecure; it makes your program vulnerable to an SQL injection attack
(From https://docs.python.org/3/library/sqlite3.html)

Better use parameter substituion as you already did just one line below.

https://github.com/LuBlaBo/Zeiterfassung/blob/229da34fa7ebb266c616c8f05182b4eb3899d624/Server.py#L87

**Comment by LuBlaBo** [comment]
I have now implemented parameter substitution... Maybe it will be safer now ^^

**Comment by pintman** [comment]
523248345e1a5072ee48bf875ac76f999c84f306 looks a lot better now.  :+1:  :)
